return {
  {
    'nvim-treesitter/nvim-treesitter',
    branch = 'master',
    build = ':TSUpdate',
    main = 'nvim-treesitter.configs',
    opts = {
      ensure_installed = {
        'bash',
        'c',
        'diff',
        'html',
        'lua',
        'luadoc',
        'markdown',
        'markdown_inline',
        'query',
        'vim',
        'vimdoc',
        'kotlin',
        'java',
        'python',
        'typescript',
        'tsx',
        'sql',
        'proto',
        'graphql',
        'terraform',
        'yaml',
        'json',
        'dockerfile',
      },
      auto_install = true,
      ignore_install = { 'swift' }, -- Swift parser has compatibility issues with newer tree-sitter CLI
      highlight = { enable = true, additional_vim_regex_highlighting = { 'ruby' } },
      indent = { enable = true, disable = { 'ruby' } },
    },
  },
}
